---

- src: https://github.com/MerlinDMC/ansible-role-homebrew.git
  name: MerlinDMC.superlumic-homebrew

- src: https://github.com/superlumic/ansible-role-computername.git
  name: roderik.superlumic-computername
