---

- name: install homebrew applications for all users
  homebrew: name={{item}} state=present
  with_items:
    - fish
    - the_silver_searcher
    - wget
    - xz
    - pigz
    - jq
    - tmate
    - ngrok
